-- Справочник известных моделей смартфонов/ноутбуков — для подсказок
-- автозаполнения в форме заказа (см. suggest_device_models() в
-- functions.php). Отдельная таблица, а не запись в repairs — чтобы не
-- засорять реальные заказы фейковыми записями. Список практический
-- (актуальные и распространённые модели), а не исчерпывающий — база
-- продолжает пополняться автоматически из реальных заказов (см. §5
-- PROJECT_STATE.md, GROUP BY ... ORDER BY COUNT(*) DESC уже приоритизирует
-- то, что реально чинили, над каталожными записями).
-- Применить: mysql -u avior_user -p avior_cms < sql/migrations/2026_08_17_device_model_catalog.sql

CREATE TABLE IF NOT EXISTS device_model_catalog (
    id         INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name       VARCHAR(150) NOT NULL UNIQUE,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT IGNORE INTO device_model_catalog (name) VALUES
    ('iPhone 6'),
    ('iPhone 6 Plus'),
    ('iPhone 6s'),
    ('iPhone 6s Plus'),
    ('iPhone SE (2016)'),
    ('iPhone 7'),
    ('iPhone 7 Plus'),
    ('iPhone 8'),
    ('iPhone 8 Plus'),
    ('iPhone X'),
    ('iPhone XR'),
    ('iPhone XS'),
    ('iPhone XS Max'),
    ('iPhone 11'),
    ('iPhone 11 Pro'),
    ('iPhone 11 Pro Max'),
    ('iPhone SE (2020)'),
    ('iPhone 12 mini'),
    ('iPhone 12'),
    ('iPhone 12 Pro'),
    ('iPhone 12 Pro Max'),
    ('iPhone 13 mini'),
    ('iPhone 13'),
    ('iPhone 13 Pro'),
    ('iPhone 13 Pro Max'),
    ('iPhone SE (2022)'),
    ('iPhone 14'),
    ('iPhone 14 Plus'),
    ('iPhone 14 Pro'),
    ('iPhone 14 Pro Max'),
    ('iPhone 15'),
    ('iPhone 15 Plus'),
    ('iPhone 15 Pro'),
    ('iPhone 15 Pro Max'),
    ('iPhone 16'),
    ('iPhone 16 Plus'),
    ('iPhone 16 Pro'),
    ('iPhone 16 Pro Max'),
    ('Samsung Galaxy S8'),
    ('Samsung Galaxy S8+'),
    ('Samsung Galaxy S9'),
    ('Samsung Galaxy S9+'),
    ('Samsung Galaxy S10e'),
    ('Samsung Galaxy S10'),
    ('Samsung Galaxy S10+'),
    ('Samsung Galaxy S20'),
    ('Samsung Galaxy S20+'),
    ('Samsung Galaxy S20 Ultra'),
    ('Samsung Galaxy S20 FE'),
    ('Samsung Galaxy S21'),
    ('Samsung Galaxy S21+'),
    ('Samsung Galaxy S21 Ultra'),
    ('Samsung Galaxy S21 FE'),
    ('Samsung Galaxy S22'),
    ('Samsung Galaxy S22+'),
    ('Samsung Galaxy S22 Ultra'),
    ('Samsung Galaxy S23'),
    ('Samsung Galaxy S23+'),
    ('Samsung Galaxy S23 Ultra'),
    ('Samsung Galaxy S23 FE'),
    ('Samsung Galaxy S24'),
    ('Samsung Galaxy S24+'),
    ('Samsung Galaxy S24 Ultra'),
    ('Samsung Galaxy S24 FE'),
    ('Samsung Galaxy S25'),
    ('Samsung Galaxy S25+'),
    ('Samsung Galaxy S25 Ultra'),
    ('Samsung Galaxy A12'),
    ('Samsung Galaxy A13'),
    ('Samsung Galaxy A14'),
    ('Samsung Galaxy A22'),
    ('Samsung Galaxy A23'),
    ('Samsung Galaxy A32'),
    ('Samsung Galaxy A33'),
    ('Samsung Galaxy A34'),
    ('Samsung Galaxy A50'),
    ('Samsung Galaxy A51'),
    ('Samsung Galaxy A52'),
    ('Samsung Galaxy A53'),
    ('Samsung Galaxy A54'),
    ('Samsung Galaxy A55'),
    ('Samsung Galaxy A72'),
    ('Samsung Galaxy A73'),
    ('Samsung Galaxy Note 8'),
    ('Samsung Galaxy Note 9'),
    ('Samsung Galaxy Note 10'),
    ('Samsung Galaxy Note 10+'),
    ('Samsung Galaxy Note 20'),
    ('Samsung Galaxy Note 20 Ultra'),
    ('Samsung Galaxy Z Flip'),
    ('Samsung Galaxy Z Flip3'),
    ('Samsung Galaxy Z Flip4'),
    ('Samsung Galaxy Z Flip5'),
    ('Samsung Galaxy Z Fold2'),
    ('Samsung Galaxy Z Fold3'),
    ('Samsung Galaxy Z Fold4'),
    ('Samsung Galaxy Z Fold5'),
    ('Redmi Note 8'),
    ('Redmi Note 9'),
    ('Redmi Note 10'),
    ('Redmi Note 11'),
    ('Redmi Note 12'),
    ('Redmi Note 13'),
    ('Redmi 9'),
    ('Redmi 10'),
    ('Redmi 12'),
    ('Xiaomi Mi 9'),
    ('Xiaomi Mi 10'),
    ('Xiaomi Mi 11'),
    ('Xiaomi 12'),
    ('Xiaomi 13'),
    ('Xiaomi 14'),
    ('POCO X3'),
    ('POCO X4'),
    ('POCO X5'),
    ('POCO F4'),
    ('POCO F5'),
    ('POCO M4'),
    ('Huawei P30'),
    ('Huawei P40'),
    ('Huawei P50'),
    ('Huawei Mate 20'),
    ('Huawei Mate 30'),
    ('Huawei Mate 40'),
    ('Honor 9X'),
    ('Honor 10X'),
    ('Honor 20'),
    ('Honor 50'),
    ('Honor 70'),
    ('Honor 90'),
    ('Honor X8'),
    ('Honor X9'),
    ('Google Pixel 5'),
    ('Google Pixel 6'),
    ('Google Pixel 6 Pro'),
    ('Google Pixel 7'),
    ('Google Pixel 7 Pro'),
    ('Google Pixel 8'),
    ('Google Pixel 8 Pro'),
    ('OnePlus 8'),
    ('OnePlus 9'),
    ('OnePlus 10'),
    ('OnePlus 11'),
    ('OnePlus Nord 2'),
    ('OnePlus Nord 3'),
    ('MacBook Air 13" (2017, Intel)'),
    ('MacBook Air M1 (2020)'),
    ('MacBook Air M2 (2022)'),
    ('MacBook Air M3 (2024)'),
    ('MacBook Pro 13" (Intel)'),
    ('MacBook Pro 13" M1'),
    ('MacBook Pro 14" M1 Pro'),
    ('MacBook Pro 14" M2 Pro'),
    ('MacBook Pro 14" M3'),
    ('MacBook Pro 16" M1 Max'),
    ('MacBook Pro 16" M3 Pro'),
    ('Lenovo ThinkPad T14'),
    ('Lenovo ThinkPad T480'),
    ('Lenovo ThinkPad X1 Carbon'),
    ('Lenovo ThinkPad E14'),
    ('Lenovo ThinkPad E15'),
    ('Lenovo IdeaPad 3'),
    ('Lenovo IdeaPad 5'),
    ('Lenovo IdeaPad Flex 5'),
    ('Lenovo Legion 5'),
    ('Lenovo Legion Y540'),
    ('Lenovo Yoga Slim 7'),
    ('HP Pavilion 15'),
    ('HP Pavilion x360'),
    ('HP EliteBook 840'),
    ('HP ProBook 450'),
    ('HP Omen 15'),
    ('HP Envy 13'),
    ('HP Envy x360'),
    ('Dell Inspiron 15 3000'),
    ('Dell Inspiron 15 5000'),
    ('Dell XPS 13'),
    ('Dell XPS 15'),
    ('Dell Latitude 5420'),
    ('Dell Latitude 7420'),
    ('Dell Vostro 15'),
    ('Asus VivoBook 15'),
    ('Asus VivoBook S14'),
    ('Asus ZenBook 14'),
    ('Asus ZenBook Duo'),
    ('Asus ROG Strix G15'),
    ('Asus ROG Zephyrus G14'),
    ('Asus TUF Gaming A15'),
    ('Acer Aspire 3'),
    ('Acer Aspire 5'),
    ('Acer Aspire 7'),
    ('Acer Nitro 5'),
    ('Acer Predator Helios 300'),
    ('Acer Swift 3'),
    ('Acer Swift 5'),
    ('MSI Modern 14'),
    ('MSI Katana GF66'),
    ('MSI Cyborg 15'),
    ('MSI Stealth 15'),
    ('MSI GF63 Thin');
